// Generated by Copilot


using System;
using System.IO;
using Rotherprivat.Copy2AlbumFolder;
using Xunit;

namespace Copy2AlbumFolder.Tests
{
    public class AlbumGeneratorTests
    {
        private static string TestDataDirectory => Path.Combine(AppContext.BaseDirectory, "TestData");

        [Fact]
        public void ConfirmInput_ReturnsTrue_WhenInputIsYes()
        {
            var generator = new AlbumGenerator
            {
                In = new StringReader("y\n"),
                Out = new StringWriter(),
                Pattern = "yyyyMMdd_HHmmss",
                Recursive = false
            };

            var result = generator.ConfirmInput();

            Assert.True(result);
            var output = generator.Out.ToString();
            Assert.Contains("Album Generator", output);
            Assert.Contains("Outputfile example", output);
        }

        [Fact]
        public void ConfirmInput_ReturnsTrue_WhenInputIsNo()
        {
            var generator = new AlbumGenerator
            {
                In = new StringReader("n\n"),
                Out = new StringWriter(),
                Pattern = "yyyyMMdd_HHmmss",
                Recursive = false
            };

            var result = generator.ConfirmInput();

            Assert.False(result);
        }


        [Fact]
        public void Postfix_Property_AddsUnderscore_WhenSet()
        {
            var generator = new AlbumGenerator();

            generator.Postfix = "abc";

            Assert.Equal("_abc", generator.Postfix);

            generator.Postfix = null;
            Assert.Equal(string.Empty, generator.Postfix);
        }

        [Fact]
        public void GetUniqueOutputFilePath_Throws_When_AlbumDirectory_Null()
        {
            var sut = new AlbumGenerator();
            var source = new FileInfo(Path.Combine(TestDataDirectory, Guid.NewGuid().ToString() + ".jpg"));

            Assert.Throws<InvalidOperationException>(() => sut.GetUniqueOutputFilePath(source, "base"));
        }

        [Fact]
        public void GetUniqueOutputFilePath_Returns_00_When_No_Existing_File()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                var sut = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(tempDir)
                };

                var source = new FileInfo(Path.Combine(tempDir, "source.jpg"));
                var result = sut.GetUniqueOutputFilePath(source, "base");

                var expected = Path.Combine(tempDir, "base_00.jpg");
                Assert.Equal(expected, result);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void GetUniqueOutputFilePath_Skips_Existing_Indices()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                var sut = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(tempDir)
                };

                // create base_00.jpg so the method should return base_01.jpg
                var existing = Path.Combine(tempDir, "base_00.jpg");
                using (File.Create(existing)) { }

                var source = new FileInfo(Path.Combine(tempDir, "source.jpg"));
                var result = sut.GetUniqueOutputFilePath(source, "base");

                var expected = Path.Combine(tempDir, "base_01.jpg");
                Assert.Equal(expected, result);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void GetUniqueOutputFilePath_Returns_Null_When_All_Indices_Exist_And_Writes_To_Err()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                var sut = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(tempDir),
                    Err = new StringWriter()
                };

                // create base_00 .. base_99
                for (int i = 0; i < 100; i++)
                {
                    var filename = $"base_{i:D2}.jpg";
                    var path = Path.Combine(tempDir, filename);
                    using (File.Create(path)) { }
                }

                var source = new FileInfo(Path.Combine(tempDir, "source.jpg"));
                var result = sut.GetUniqueOutputFilePath(source, "base");

                Assert.Null(result);
                var errOutput = sut.Err.ToString();
                Assert.False(string.IsNullOrWhiteSpace(errOutput));
                // Basic check that the error output mentions the source or some text was written
                Assert.Contains("base", errOutput, StringComparison.OrdinalIgnoreCase);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }
    }
}
