// Generated by Copilot


using Rotherprivat.Copy2AlbumFolder;
using System;
using System.IO;
using System.Reflection.Emit;
using Xunit;

namespace Copy2AlbumFolder.Tests
{
    public class AlbumGeneratorTests
    {
        private static string TestDataDirectory => Path.Combine(AppContext.BaseDirectory, "TestData");

        [Fact]
        public void ConfirmInput_ReturnsTrue_WhenInputIsYes()
        {
            using var generator = new AlbumGenerator
            {
                In = new StringReader("y\n"),
                Out = new StringWriter(),
                Pattern = "yyyyMMdd_HHmmss",
                Recursive = false
            };

            var result = generator.ConfirmInput();

            Assert.True(result);
            var output = generator.Out.ToString();
            Assert.Contains("Copy2AlbumFolder", output);
            Assert.Contains("Outputfile example", output);
        }

        [Fact]
        public void ConfirmInput_ReturnsTrue_WhenInputIsNo()
        {
            using var generator = new AlbumGenerator
            {
                In = new StringReader("n\n"),
                Out = new StringWriter(),
                Pattern = "yyyyMMdd_HHmmss",
                Recursive = false
            };

            var result = generator.ConfirmInput();

            Assert.False(result);
        }


        [Fact]
        public void Postfix_Property_AddsUnderscore_WhenSet()
        {
            using var generator = new AlbumGenerator();

            generator.Postfix = "abc";

            Assert.Equal("_abc", generator.Postfix);

            generator.Postfix = null;
            Assert.Equal(string.Empty, generator.Postfix);
        }

        [Fact]
        public void GetUniqueOutputFilePath_Throws_When_AlbumDirectory_Null()
        {
            using var sut = new AlbumGenerator();
            var source = new FileInfo(Path.Combine(TestDataDirectory, Guid.NewGuid().ToString() + ".jpg"));

            Assert.Throws<InvalidOperationException>(() => sut.GetUniqueOutputFilePath(source, "base"));
        }

        [Fact]
        public void GetUniqueOutputFilePath_Returns_00_When_No_Existing_File()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                using var sut = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(tempDir)
                };

                var source = new FileInfo(Path.Combine(tempDir, "source.jpg"));
                var result = sut.GetUniqueOutputFilePath(source, "base");

                var expected = Path.Combine(tempDir, "base_00.jpg");
                Assert.Equal(expected, result);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void GetUniqueOutputFilePath_Skips_Existing_Indices()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                using var sut = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(tempDir)
                };

                // create base_00.jpg so the method should return base_01.jpg
                var existing = Path.Combine(tempDir, "base_00.jpg");
                using (File.Create(existing)) { }

                var source = new FileInfo(Path.Combine(tempDir, "source.jpg"));
                var result = sut.GetUniqueOutputFilePath(source, "base");

                var expected = Path.Combine(tempDir, "base_01.jpg");
                Assert.Equal(expected, result);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void GetUniqueOutputFilePath_Returns_Null_When_All_Indices_Exist_And_Writes_To_Err()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                using var sut = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(tempDir),
                    Err = new StringWriter()
                };

                // create base_00 .. base_99
                for (int i = 0; i < 100; i++)
                {
                    var filename = $"base_{i:D2}.jpg";
                    var path = Path.Combine(tempDir, filename);
                    using (File.Create(path)) { }
                }

                var source = new FileInfo(Path.Combine(tempDir, "source.jpg"));
                var result = sut.GetUniqueOutputFilePath(source, "base");

                Assert.Null(result);
                var errOutput = sut.Err.ToString();
                Assert.False(string.IsNullOrWhiteSpace(errOutput));
                // Basic check that the error output mentions the source or some text was written
                Assert.Contains("base", errOutput, StringComparison.OrdinalIgnoreCase);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void GetFsNameInfoString_Null_ReturnsNull()
        {
            Assert.Null(AlbumGenerator.GetFsNameInfoString(null));
        }

        [Fact]
        public void GetFsNameInfoString_FileDoesNotExist_ReturnsFullNameWithNew()
        {
            var path = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString("N") + ".jpg");
            var fileInfo = new FileInfo(path);

            var expected = fileInfo.FullName + $" ({Rotherprivat.Copy2AlbumFolder.Resources.Copy2AlbumFolder.New})";
            var actual = AlbumGenerator.GetFsNameInfoString(fileInfo);

            Assert.Equal(expected, actual);
        }

        [Fact]
        public void GetFsNameInfoString_FileExists_ReturnsFullNameWithExists()
        {
            var path = Path.Combine(TestDataDirectory, "SourceFolder", "20250924_173020.jpg");
            var fileInfo = new FileInfo(path);
            var expected = fileInfo.FullName + $" ({Rotherprivat.Copy2AlbumFolder.Resources.Copy2AlbumFolder.Exists})";
            var actual = AlbumGenerator.GetFsNameInfoString(fileInfo);

            Assert.Equal(expected, actual);
        }

        [Fact]
        public void GetFsNameInfoString_DirectoryDoesNotExist_ReturnsFullNameWithNew()
        {
            var path = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString("N"));
            var dirInfo = new DirectoryInfo(path);

            var expected = dirInfo.FullName + $" ({Rotherprivat.Copy2AlbumFolder.Resources.Copy2AlbumFolder.New})";
            var actual = AlbumGenerator.GetFsNameInfoString(dirInfo);

            Assert.Equal(expected, actual);
        }

        [Fact]
        public void GetFsNameInfoString_DirectoryExists_ReturnsFullNameWithExists()
        {
            var path = Path.Combine(TestDataDirectory, "SourceFolder");
            var dirInfo = new DirectoryInfo(path);

            var expected = dirInfo.FullName + $" ({Rotherprivat.Copy2AlbumFolder.Resources.Copy2AlbumFolder.Exists})";
            var actual = AlbumGenerator.GetFsNameInfoString(dirInfo);

            Assert.Equal(expected, actual);
        }

        // Tests for ConditionallyCreateLogFile

        [Fact]
        public void ConditionallyCreateLogFile_ReturnsTrue_When_LogFileIsNull()
        {
            using var generator = new AlbumGenerator
            {
                LogFile = null,
                Out = new StringWriter(),
                Err = new StringWriter()
            };

            var result = generator.ConditionallyCreateLogFile();

            Assert.True(result);
            // When LogFile is null the Log property should fall back to Out
            Assert.Same(generator.Out, generator.Log);
        }

        [Fact]
        public void ConditionallyCreateLogFile_Creates_LogFile_And_Writer_Appends()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            var logPath = Path.Combine(tempDir, "log.txt");

            try
            {
                using (var generator = new AlbumGenerator
                            {
                                LogFile = new FileInfo(logPath),
                                Out = new StringWriter(),
                                Err = new StringWriter()
                            })
                { 

                    // should create directory and file and open writer
                    Assert.True(generator.ConditionallyCreateLogFile());

                    Assert.NotSame(generator.Out, generator.Log);

                    // write a line and ensure it ends up in the file
                    generator.Log.WriteLine("first-line");
                }

                var content = File.ReadAllText(logPath);
                Assert.Contains("first-line", content);

                // reopen generator reusing same log file - should return true again and append
                using (var generator2 = new AlbumGenerator
                            {
                                LogFile = new FileInfo(logPath),
                                Out = new StringWriter(),
                                Err = new StringWriter()
                            })
                {
                    Assert.True(generator2.ConditionallyCreateLogFile());
                    Assert.NotSame(generator2.Out, generator2.Log);
                    generator2.Log.WriteLine("second-line");
                }

                var content2 = File.ReadAllText(logPath);
                Assert.Contains("first-line", content2);
                Assert.Contains("second-line", content2);
            }
            finally
            {
                if (Directory.Exists(tempDir))
                    Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void ConditionallyCreateLogFile_ReturnsFalse_When_LogFile_Is_Locked()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            var logPath = Path.Combine(tempDir, "log.txt");

            // create and lock the file exclusively to force StreamWriter to fail
            using var fs = new FileStream(logPath, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
            try
            {
                using var generator = new AlbumGenerator
                {
                    LogFile = new FileInfo(logPath),
                    Out = new StringWriter(),
                    Err = new StringWriter()
                };

                var result = generator.ConditionallyCreateLogFile();

                Assert.False(result);

                var errOutput = generator.Err.ToString();
                // error output should mention the log file path (formatted message)
                Assert.Contains(logPath, errOutput, StringComparison.OrdinalIgnoreCase);

                // when creation failed the Log property should fall back to Out
                Assert.Same(generator.Out, generator.Log);
            }
            finally
            {
                fs.Dispose();
                if (Directory.Exists(tempDir))
                    Directory.Delete(tempDir, recursive: true);
            }
        }
        [Fact]
        public void ConditionallyCreateAlbumDirectory_ThrowsWhenAlbumDirectoryNull()
        {
            using var generator = new AlbumGenerator();

            var ex = Assert.Throws<InvalidOperationException>(() => generator.ConditionallyCreateAlbumDirectory());
            Assert.Equal("AlbumDirectory can not be null", ex.Message);
        }

        [Fact]
        public void ConditionallyCreateAlbumDirectory_ReturnsTrueWhenDirectoryAlreadyExists()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                var path = Path.Combine(tempDir, "existing");
                Directory.CreateDirectory(path);

                using var generator = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(path),
                    Err = TextWriter.Null
                };

                var result = generator.ConditionallyCreateAlbumDirectory();

                Assert.True(result);
                Assert.True(Directory.Exists(path));
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void ConditionallyCreateAlbumDirectory_CreatesDirectoryWhenNotExists()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                var path = Path.Combine(tempDir, "newdir");

                using var generator = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(path),
                    Err = TextWriter.Null
                };

                var result = generator.ConditionallyCreateAlbumDirectory();

                Assert.True(result);
                Assert.True(Directory.Exists(path));
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

        [Fact]
        public void ConditionallyCreateAlbumDirectory_ReturnsFalseAndWritesErrorWhenCreateFails()
        {
            var tempDir = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);
            try
            {
                // Create a file with the same name as the directory we want to create.

                var targetPath = Path.Combine(tempDir, "conflict");
                File.WriteAllText(targetPath, "this file will block directory creation");

                using var generator = new AlbumGenerator
                {
                    AlbumDirectory = new DirectoryInfo(targetPath),
                    Err = new StringWriter()
                };

                var result = generator.ConditionallyCreateAlbumDirectory();

                Assert.False(result);

                var errOutput = ((StringWriter)generator.Err).ToString();
                Assert.Contains(targetPath, errOutput);
            }
            finally
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }

    }
}
