// Generated by Copilot
//
using Rotherprivat.Copy2AlbumFolder;
using System;
using System.CommandLine;
using System.Diagnostics;
using System.IO;
using System.Linq;
using Xunit;

namespace Copy2AlbumFolder.Tests
{
    public class Copy2AlbumFolderCommandTests
    {
        private static string TestDataDirectory => Path.Combine(AppContext.BaseDirectory, "TestData");

        [Fact]
        public void SourceDirectoryValidator_ReportsError_WhenSourceDoesNotExist()
        {
            var root = Copy2AlbumFolderCommand.BuildRootCommand();

            var sourcePath = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString()); // does not exist
            var albumPath = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString()); // does not exist
            var args = new[] { "--source", sourcePath, "--album", albumPath };

            var parseResult = root.Parse(args);

            Assert.True(parseResult.Errors.Any(e => e.Message.Contains("--source")), "Expected an error mentioning --source for non-existing directory.");
        }

        [Fact]
        public void PatternValidator_ReportsError_WhenPatternProducesInvalidFileName()
        {
            var root = Copy2AlbumFolderCommand.BuildRootCommand();

            var sourcePath = Path.Combine(TestDataDirectory, "SourceFolder");
            var albumPath = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString()); // does not exist

            // Pattern with slashes will create invalid file name characters (e.g. yyyy\MM\dd)
            var args = new[] { "--source", sourcePath, "--album", albumPath, "--pattern", @"yyyy\\MM\\dd" };

            var parseResult = root.Parse(args);

            Assert.True(parseResult.Errors.Any(e => e.Message.Contains("--pattern")), "Expected an error mentioning --pattern for invalid generated file name.");
        }

        [Fact]
        public void PostfixValidator_ReportsError_WhenPostfixHasInvalidChars()
        {
            var root = Copy2AlbumFolderCommand.BuildRootCommand();

            var sourcePath = Path.Combine(TestDataDirectory, "SourceFolder");
            var albumPath = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString()); // does not exist

            // Invalid postfix (contains $)
            var args = new[] { "--source", sourcePath, "--album", albumPath, "--postfix", "abc$" };

            var parseResult = root.Parse(args);

            // The validator in the implementation is attached to the pattern option and reports using that option's name.
            Assert.True(parseResult.Errors.Any(e => e.Message.Contains("--pattern") || e.Message.Contains("--postfix") || parseResult.Errors.Count > 0),
                "Expected an error for invalid postfix characters.");
        }

        [Fact]
        public void PatternOption_DefaultsTo_yyyyMMdd_HHmmss()
        {
            var root = Copy2AlbumFolderCommand.BuildRootCommand();

            var sourcePath = Path.Combine(TestDataDirectory, "SourceFolder");
            var albumPath = Path.Combine(TestDataDirectory, Guid.NewGuid().ToString()); // does not exist

            var args = new[] { "--source", sourcePath, "--album", albumPath };
            var parseResult = root.Parse(args);

            var patternOption = root.Options.First(o => string.Equals(o.Name, "--pattern", StringComparison.OrdinalIgnoreCase)) as Option<string>;
            var value = parseResult.GetValue(patternOption) as string;

            Assert.Equal("yyyyMMdd_HHmmss", value);
        }
    }
}