//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rotherprivat.Copy2AlbumFolder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Copy2AlbumFolder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Copy2AlbumFolder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rotherprivat.Copy2AlbumFolder.Resources.Copy2AlbumFolder", typeof(Copy2AlbumFolder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album folder, output folder..
        /// </summary>
        internal static string AlbumDirectoryOption {
            get {
                return ResourceManager.GetString("AlbumDirectoryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merges picture folders to a common album folder and use the timestamp of the image- or video- metadata as file names, to get sortable and unique file names..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y,yes.
        /// </summary>
        internal static string ConfirmationAnswer {
            get {
                return ResourceManager.GetString("ConfirmationAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y/N.
        /// </summary>
        internal static string ConfirmationPrompt {
            get {
                return ResourceManager.GetString("ConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy2AlbumFolder:
        ///  Source folder: {0}
        ///  Album folder: {1}
        ///  Log file: {2}
        ///  Recursive: {3}
        ///  Outputfile example: {4}
        ///Continue ({5}) ? .
        /// </summary>
        internal static string ConfirmationText {
            get {
                return ResourceManager.GetString("ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create or access the log file {0}..
        /// </summary>
        internal static string ErrorAccessLogFile {
            get {
                return ResourceManager.GetString("ErrorAccessLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file {0}..
        /// </summary>
        internal static string ErrorCopyFile {
            get {
                return ResourceManager.GetString("ErrorCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create album folder {0}..
        /// </summary>
        internal static string ErrorCreateAlbumDirectory {
            get {
                return ResourceManager.GetString("ErrorCreateAlbumDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index number exceeded..
        /// </summary>
        internal static string ErrorFileIndexExceeded {
            get {
                return ResourceManager.GetString("ErrorFileIndexExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will lead to invalid filenames..
        /// </summary>
        internal static string ErrorInvalidFileNames {
            get {
                return ResourceManager.GetString("ErrorInvalidFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing DateTime meta tag..
        /// </summary>
        internal static string ErrorMissingDateTimeTag {
            get {
                return ResourceManager.GetString("ErrorMissingDateTimeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See.
        /// </summary>
        internal static string ErrorPatternOptionSeeLink {
            get {
                return ResourceManager.GetString("ErrorPatternOptionSeeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 1 to 5 characters &apos;a&apos;-&apos;z&apos;, &apos;A&apos;-&apos;Z&apos;, &apos;0&apos;-&apos;9&apos;, &apos;-&apos; and &apos;_&apos; are allowed..
        /// </summary>
        internal static string ErrorPostfixOptionAllowedChars {
            get {
                return ResourceManager.GetString("ErrorPostfixOptionAllowedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta data can not be processed..
        /// </summary>
        internal static string ErrorProcessingMetaData {
            get {
                return ResourceManager.GetString("ErrorProcessingMetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read file..
        /// </summary>
        internal static string ErrorReadFile {
            get {
                return ResourceManager.GetString("ErrorReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory dos not exist..
        /// </summary>
        internal static string ErrorSourceDirectoryOptionNoDirectory {
            get {
                return ResourceManager.GetString("ErrorSourceDirectoryOptionNoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exists.
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write, append copy operations to log file..
        /// </summary>
        internal static string LogFileOption {
            get {
                return ResourceManager.GetString("LogFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern for output file names..
        /// </summary>
        internal static string PatternOption {
            get {
                return ResourceManager.GetString("PatternOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix of output filename..
        /// </summary>
        internal static string PostfixOption {
            get {
                return ResourceManager.GetString("PostfixOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copys source files recursive..
        /// </summary>
        internal static string RecursiveOption {
            get {
                return ResourceManager.GetString("RecursiveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder, containing a part of the album..
        /// </summary>
        internal static string SourceDirectoryOption {
            get {
                return ResourceManager.GetString("SourceDirectoryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppresses the interactive input confirmation..
        /// </summary>
        internal static string SuppressConfirmInputOption {
            get {
                return ResourceManager.GetString("SuppressConfirmInputOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
